### ISSUE TITLE
Update essential services delivery instances to use ACA-Py 0.7.3(-rc0 or not) and two ledgers

### ISSUE THREAD

**Issue by swcurran** [bcgov/essential-services-delivery#109]
Please update the "essential services" delivery instances to all use two ledgers for reading - Sovrin Staging (current) and CANdy-Dev (new).  All of the existing instances should continue to write to Sovrin Staging (if necessary at all -- only those with revocation should need that).  In doing this, all instances of ACA-Py need to be upgraded to 0.7.3-RC0 (for now) and 0.7.3 when available.

Per #108 -- please add a new deployment to this repo for a new unverified person, where that instance using both Sovrin Staging and CANdy-Dev (per the others), but that writes to CANdy-Dev.

In implementing these changes, please consider what improvements could be made to the management. What would change if we use a multi-tenant ACA-Py instance?  What if we were using the (being designed) Traction API?

**Comment by ianco** [comment]
Apparently these are all issuer services (issue only no verify) so not sure if adding multi-ledger support makes sense.

The verifier service (that will need the multi-ledger configuration) is here:  https://github.com/bcgov/a2a-trust-over-ip-configurations (I believe, @esune ?)

**Comment by ianco** [comment]
Regarding multitenancy, I think you'd need a controller to manage the issuer instances within the multi-tenant aca-py, so a bigger task than just updating some configurations, probably worth a discussion to make sure we're all on the same page regarding the required work etc.

On the plus side you'd be able to (via the new controller) add a new issuer instance fairly easily ...

**Comment by esune** [comment]
> Apparently these are all issuer services (issue only no verify) so not sure if adding multi-ledger support makes sense.
> 
> The verifier service (that will need the multi-ledger configuration) is here: https://github.com/bcgov/a2a-trust-over-ip-configurations (I believe, @esune ?)

This is correct: these are just issuer services, so it doesn't make much sense to add multi-ledger support - I think it will just turn into a headache.

Verification is obtained for all these services through `vc-authn` as part of an OIDC authentication flow. It makes sense to support multi-ledger on those verifiers, for which the configurations are at the link above by @ianco .

The [agent](https://github.com/bcgov/a2a-trust-over-ip-configurations/tree/master/openshift/templates/agent) and [agent-rev](https://github.com/bcgov/a2a-trust-over-ip-configurations/tree/master/openshift/templates/agent-rev) configurations can be updated to both use the new aca-py image (see #108 for details on how to do that) and would then be updated to pick up the ledger list from a file. To do this:
1. I would recommend using the environment variables rather than the start command parameters to specify the path to the file containing the configuration.
2. The file will need to be used to generate a configmap that is then mounted to the pod: this needs to be added to the deployment configuration, an example of this is in the essential-services `api` configuration.
2.1 An [overrides.sh](https://github.com/bcgov/essential-services-delivery/blob/main/openshift/templates/api/api-deploy.overrides.sh) file is used to generate the configmap template, based on files in a named-profile configuration folder ([like this one](https://github.com/bcgov/essential-services-delivery/tree/main/openshift/templates/api/config/openvp)).
2.2 A [volume](https://github.com/bcgov/essential-services-delivery/blob/main/openshift/templates/api/api-deploy.yaml#L137-L142) definition and a matching [volumeMount](https://github.com/bcgov/essential-services-delivery/blob/main/openshift/templates/api/api-deploy.yaml#L233-L235) definition will be created to mount the configmap on the running pod.

If possible, I would recommend updating both the profiles (`agent` and `agent-rev`) so that they are kept in sync (due to how wallets handle revocation, we need two verifier agents to handle proof-requests with and without revocation).

**Comment by esune** [comment]
> Regarding multitenancy, I think you'd need a controller to manage the issuer instances within the multi-tenant aca-py, so a bigger task than just updating some configurations, probably worth a discussion to make sure we're all on the same page regarding the required work etc.
> 
> On the plus side you'd be able to (via the new controller) add a new issuer instance fairly easily ...

I agree it is not a trivial change as it requires more than just configurations (e.g.: `issuer-kit` needs to be updated to support multi-tenant agents rather than one agent per issuer).

**Comment by swcurran** [comment]
Got it about the verifiers -- ignore the comment on the other issue I made a few minutes ago. 

The multi-tenancy angle was meant as a thought experiment, not a "please do it" request.  I suspect that we wouldn't want to, but it would be good as we go into the Traction Agency work, what it would take.  As you mention, probably not a lot less effort -- just that the deployment is just the controller and UI, and the rest of the infrastructure is just a pointer to the Agency.  Something like that..??

**Comment by esune** [comment]
Yes, assuming the code supported already the correct headers to authenticate with the appropriate tenant on a deployed agent, controller + web frontend (and supporting services like the db, if not shared) is what would need to be deployed.

**Comment by WadeBarnes** [comment]
The agents have been updated to 0.7.3-RC0
